_name_or_path:
    value: stabilityai/stablelm-2-1_6b
_wandb:
    value:
        cli_version: 0.18.2
        m:
            - "1": train/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": train/epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/samples_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/runtime
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/steps_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/grad_norm
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "3":
                - 2
                - 7
                - 13
                - 16
                - 19
                - 23
                - 55
                - 62
                - 66
            "4": 3.10.12
            "5": 0.18.2
            "6": 4.44.2
            "8":
                - 1
                - 5
                - 12
            "9":
                "1": transformers_trainer
            "12": 0.18.2
            "13": linux-x86_64
GPUs:
    value: 1
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - StableLmForCausalLM
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 100257
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset:
    value: LLM Model Training
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
dispatch_batches:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 100278
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: epoch
eval_use_gather_object:
    value: false
evaluation_strategy:
    value: null
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
ga_steps:
    value: 4
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: silu
hidden_dropout:
    value: 0
hidden_size:
    value: 2048
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 5632
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_eps:
    value: 1e-05
learning_rate:
    value: 0.0002
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /content/drive/My Drive/TDP Capstone Grp 7/LLM Model Training/qLoRA/wandb/out-a045f627-1c1d-4d82-bcb4-b76e23e44540/runs/Sep29_14-23-07_9a0f6f065574
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 500
logging_strategy:
    value: epoch
lr:
    value: 0.0002
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 4096
max_steps:
    value: -1
metric_for_best_model:
    value: loss
min_length:
    value: 0
model/num_parameters:
    value: 1645301760
model_name:
    value: StableLM2_TDP
model_type:
    value: stablelm
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 32
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 24
num_key_value_heads:
    value: 32
num_return_sequences:
    value: 1
num_train_epochs:
    value: 5
optim:
    value: paged_adamw_8bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: /content/drive/My Drive/TDP Capstone Grp 7/LLM Model Training/qLoRA/wandb/out-a045f627-1c1d-4d82-bcb4-b76e23e44540
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
partial_rotary_factor:
    value: 0.25
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: stabilityai/stablelm-2-1_6b
            bias: none
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_dropout: 0.05
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            r: 8
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - q_proj
            task_type: CAUSAL_LM
            use_dora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 4
per_device_train_batch_size:
    value: 4
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
qk_layernorm:
    value: false
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - tensorboard
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rope_scaling:
    value: null
rope_theta:
    value: 10000
run_id:
    value: a045f627-1c1d-4d82-bcb4-b76e23e44540
run_name:
    value: /content/drive/My Drive/TDP Capstone Grp 7/LLM Model Training/qLoRA/wandb/out-a045f627-1c1d-4d82-bcb4-b76e23e44540
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: null
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
split_batches:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float16
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
train_batch_size:
    value: 4
training_args:
    value:
        _n_gpu: 1
        accelerator_config:
            dispatch_batches: null
            even_batches: true
            gradient_accumulation_kwargs: null
            non_blocking: false
            split_batches: false
            use_configured_state: false
            use_seedable_sampler: true
        adafactor: false
        adam_beta1: 0.9
        adam_beta2: 0.999
        adam_epsilon: 1e-08
        auto_find_batch_size: false
        batch_eval_metrics: false
        bf16: false
        bf16_full_eval: false
        data_seed: null
        dataloader_drop_last: false
        dataloader_num_workers: 0
        dataloader_persistent_workers: false
        dataloader_pin_memory: true
        dataloader_prefetch_factor: null
        ddp_backend: null
        ddp_broadcast_buffers: null
        ddp_bucket_cap_mb: null
        ddp_find_unused_parameters: null
        ddp_timeout: 1800
        debug: []
        deepspeed: null
        disable_tqdm: false
        dispatch_batches: null
        do_eval: true
        do_predict: false
        do_train: false
        eval_accumulation_steps: null
        eval_delay: 0
        eval_do_concat_batches: true
        eval_on_start: false
        eval_steps: null
        eval_strategy: epoch
        eval_use_gather_object: false
        evaluation_strategy: null
        fp16: true
        fp16_backend: auto
        fp16_full_eval: false
        fp16_opt_level: O1
        fsdp: []
        fsdp_config:
            min_num_params: 0
            xla: false
            xla_fsdp_grad_ckpt: false
            xla_fsdp_v2: false
        fsdp_min_num_params: 0
        fsdp_transformer_layer_cls_to_wrap: null
        full_determinism: false
        gradient_accumulation_steps: 4
        gradient_checkpointing: false
        gradient_checkpointing_kwargs: null
        greater_is_better: false
        group_by_length: false
        half_precision_backend: auto
        hub_always_push: false
        hub_model_id: null
        hub_private_repo: false
        hub_strategy: every_save
        hub_token: null
        ignore_data_skip: false
        include_inputs_for_metrics: false
        include_num_input_tokens_seen: false
        include_tokens_per_second: false
        jit_mode_eval: false
        label_names: null
        label_smoothing_factor: 0
        learning_rate: 0.0002
        length_column_name: length
        load_best_model_at_end: true
        local_rank: 0
        log_level: passive
        log_level_replica: warning
        log_on_each_node: true
        logging_dir: /content/drive/My Drive/TDP Capstone Grp 7/LLM Model Training/qLoRA/wandb/out-a045f627-1c1d-4d82-bcb4-b76e23e44540/runs/Sep29_14-23-07_9a0f6f065574
        logging_first_step: false
        logging_nan_inf_filter: true
        logging_steps: 500
        logging_strategy: epoch
        lr_scheduler_type: linear
        max_grad_norm: 1
        max_steps: -1
        metric_for_best_model: loss
        mp_parameters: ""
        neftune_noise_alpha: null
        no_cuda: false
        num_train_epochs: 5
        optim: paged_adamw_8bit
        optim_args: null
        optim_target_modules: null
        output_dir: /content/drive/My Drive/TDP Capstone Grp 7/LLM Model Training/qLoRA/wandb/out-a045f627-1c1d-4d82-bcb4-b76e23e44540
        overwrite_output_dir: false
        past_index: -1
        per_device_eval_batch_size: 4
        per_device_train_batch_size: 4
        per_gpu_eval_batch_size: null
        per_gpu_train_batch_size: null
        prediction_loss_only: false
        push_to_hub: false
        push_to_hub_model_id: null
        push_to_hub_organization: null
        push_to_hub_token: null
        ray_scope: last
        remove_unused_columns: true
        report_to:
            - tensorboard
            - wandb
        restore_callback_states_from_checkpoint: false
        resume_from_checkpoint: null
        run_name: /content/drive/My Drive/TDP Capstone Grp 7/LLM Model Training/qLoRA/wandb/out-a045f627-1c1d-4d82-bcb4-b76e23e44540
        save_on_each_node: false
        save_only_model: false
        save_safetensors: true
        save_steps: 500
        save_strategy: epoch
        save_total_limit: null
        seed: 42
        skip_memory_metrics: true
        split_batches: null
        tf32: null
        torch_compile: false
        torch_compile_backend: null
        torch_compile_mode: null
        torch_empty_cache_steps: null
        torchdynamo: null
        tpu_metrics_debug: false
        tpu_num_cores: null
        use_cpu: false
        use_ipex: false
        use_legacy_prediction_loop: false
        use_mps_device: false
        warmup_ratio: 0
        warmup_steps: 2
        weight_decay: 0.01
transformers_version:
    value: 4.44.2
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
use_parallel_residual:
    value: false
use_qkv_bias:
    value: true
validation_batch_size:
    value: 4
vocab_size:
    value: 100352
warmup_ratio:
    value: 0
warmup_steps:
    value: 2
weight_decay:
    value: 0.01
